# Generated by Django 5.2 on 2025-05-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('moderator', 'Модератор'), ('teacher', 'Преподаватель'), ('student', 'Студент'), ('waiting', 'Без роли')], default='waiting', max_length=20),
        ),
    ]
